### PR TITLE
new build file

### PR DESCRIPTION
**Pull request by aruntk**
#### Questions:
- Does this add any dependencies ?

### CODE REVIEW

**Comment by JakeHartnell** [comment]
What's with all the Sortable stuff? Changes to the build file look cool. Thanks for that again.

**Comment by JakeHartnell** [comment]
I hit the merge button anyway, there is an open issue that's related to Sortable stuff: https://github.com/CommonGarden/Grow-IoT/issues/283

**Comment by aruntk** [comment]
@JakeHartnell There was a folder named meteor inside sortable which contained a lot of unnecessary js files. Deleted that one also. How is the build time now?

**Comment by JakeHartnell** [comment]
> How is the build time now?

Good!

**Pull request merged**
