### PR TITLE
things by type

### PR DESCRIPTION
**Pull request by aruntk**
### User Story

- [x] test device selects graphs, according to event type.

- [x] grow elements demand data they need from test device. import/ui/components/grow-elements/demand-behaviors.js

- [x] tests/test-device.js takes in arguments. 
`node tests/test-device.js [uuid] [token] [type] `

example: 
```sh
node tests/test-device.js 6e42b6d8-1c3b-4a69-9527-4b8d20f8486c nLoyuaKpuMG4nCZTYfuRHQtoMFKPbb2j temperature
```

- [x] test-device for all event types. Previously it was temperature only. test device changes its contents according to event type.

#### Questions:
- Does this add any dependencies ?

### CODE REVIEW

**Comment by JakeHartnell** [comment]
Thanks! This was _really_ helpful. This is more along the lines of what I was thinking of: https://github.com/CommonGarden/Grow-IoT/commit/c1abbd66adc6735396acd4dc9f645e30ea2b8249

See `thing-display.html` and `thing-display.js`.

**Comment by aruntk** [comment]
@JakeHartnell What about taking uuid and token as arguments from command in tests/test-device.js.? https://github.com/CommonGarden/Grow-IoT/blob/f61d62b396b85f6c160cf174e8dda20b14794483/tests/test-device.js . Isn't it is better than copy pasting uuid&token every time someone wants to start testing?

**Comment by JakeHartnell** [comment]
> @JakeHartnell What about taking uuid and token as arguments from command in tests/test-device.js.? https://github.com/CommonGarden/Grow-IoT/blob/f61d62b396b85f6c160cf174e8dda20b14794483/tests/test-device.js . Isn't it is better than copy pasting uuid&token every time someone wants to start testing?

Good idea. We need better testing infrastructure...

**Comment by aruntk** [comment]
@JakeHartnell A start https://github.com/CommonGarden/Grow-IoT/tree/arun-tests.

**Pull request closed without merging**
