### PR TITLE
Possible Typo Fix

### PR DESCRIPTION
**Pull request by scottdevito**
Object property in light.js example read 'desription' instead of 'description'.

### CODE REVIEW

**Comment by JakeHartnell** [comment]
Thanks!

**Comment by scottdevito** [comment]
No problem!

**Comment by JakeHartnell** [comment]
@psilotec any thoughts on https://github.com/CommonGarden/Grow-IoT/issues/216?

**Comment by scottdevito** [comment]
I was taking a look at that issue before.  I wish I could be of more help but, i'm really just getting started playing around with all the options out there.  I enjoy agriculture and I really appreciate what this project is about so I've been going through it and using it to learn.  Thanks for that.  I'm looking at the raspberry pi and a few types of sensors (temp, photo resistor, humidity, water/moisture) but none in particular.

**Pull request merged**
