### PR TITLE
Update license

### PR DESCRIPTION
**Pull request by newswim**
Hey CG!

The copyright date on most of the license files within this project were dated 2016. I updated those (#435) are made a little modification to the eslintrc in order to appease newer syntax (#437).

### CODE REVIEW

**Comment by newswim** [comment]
Created an issue for fixing the failing Travis build.

See https://github.com/CommonGarden/Grow-IoT/issues/440

**Comment by JakeHartnell** [comment]
What other changes would you make to eslint so we can close #437?

**Comment by newswim** [comment]
I fixed the first warning by changing line:

```"quotes": ["error", "single"],```

, but the second one would require a major version update. Upgrading is probably preferred over switching to Prettier, since that could reformat the entire codebase and contributors might have difficulty installing the dependencies (although it is widely used).

**Comment by JakeHartnell** [comment]
Thanks for this! Close #439.

**Pull request merged**
